/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int main()
{
    long int sum = 2;
    int k = 3;

    for (int i = 1, j = 2; k <= 4000000; i = j, j = k, k = i + j) {
        if (k % 2 == 0) {
            sum += k;
        }
    }

    printf("The sum of the even-valued terms in the Fibonacci sepence whose ");
    printf("values do not exceed four million is %ld.\n", sum);

    return 0;
}
