/**
 * @file problem12.c
 * @author Yang Yunyi (yunyiyang@ln.hk)
 * @brief Project Euler Problem 12 - Highly divisible triangular number
 * 
 * The sequence of triangle numbers is generated by adding the natural
 * numbers. So the 7th triangle number would be
 * 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five
 * divisors.
 * 
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 * 
 * @date 2022-01-12
 * 
 * @copyright Copyright (c) 2022
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <stdio.h>

int getnod(int num); /* get number of divisors */
int gettri(int n); /* get nth triangle number */

int main() {
    int tri, nod;
    for (int i = 1; ; ++i) {
        tri = gettri(i);
        nod = getnod(tri);
        if (nod > 500) {
            printf("%d", tri);
            return 0;
        }
    }
}

int getnod(int num) {
    int nod = 0;
    if (num <= 0) {
        return -1;
    }
    for (int i = 1; i <= num; ++i) {
        if (num % i == 0) {
            ++nod;
        }
    }
    return nod;
}

int gettri(int n) {
    int tri = 0;
    for (int i = 1; i <= n; ++i) {
        tri += i;
    }
    return tri;
}
